name: 'Pull Request Labeler'
on:
    pull_request:

permissions:
    pull-requests: write

jobs:
    auto-labeler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
