name: 'Pull Request Labeler'
on:
    pull_request:
    workflow_run:
        workflows: ['Sync Branches']
        types:
            - completed

permissions:
    pull-requests: write

jobs:
    auto-labeler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
