name: Mark PR as Deployed to Dev

on:
    push:
        branches:
            - main

jobs:
    mark-deployment:
        name: Mark as Deployed
        runs-on: ubuntu-latest
        environment: dev # must match GitHub Environment name

        steps:
            - name: Create fake deployment
              uses: actions/github-script@v7
              with:
                  script: |
                      const { owner, repo } = context.repo;

                      const deployment = await github.rest.repos.createDeployment({
                        owner,
                        repo,
                        ref: context.sha,
                        required_contexts: [],
                        environment: 'dev',
                        auto_merge: false,
                        transient_environment: false,
                        production_environment: false,
                        description: 'PR merged to main - marked as dev deployment',
                      });

                      await github.rest.repos.createDeploymentStatus({
                        owner,
                        repo,
                        deployment_id: deployment.data.id,
                        state: 'success',
                        environment_url: '', // optional, can add a preview URL
                        description: 'Marked as deployed to dev',
                      });
