name: Mark PR as Deployed to Dev

on:
    pull_request:
        types:
            - closed
        branches:
            - main

permissions:
    contents: read
    deployments: write # Needed to use createDeployment API

jobs:
    mark-deployment:
        if: github.event.pull_request.merged == true # ✅ Only run on merged PRs
        runs-on: ubuntu-latest
        environment:
            name: dev

        steps:
            - name: Mark deployment in Jira
              uses: actions/github-script@v7
              with:
                  script: |
                      const { owner, repo } = context.repo;
                      const pr = context.payload.pull_request;
                      const ref = pr.merge_commit_sha;

                      const deployment = await github.rest.repos.createDeployment({
                        owner,
                        repo,
                        ref: ref,
                        required_contexts: [],
                        environment: 'dev',
                        auto_merge: false,
                        transient_environment: false,
                        production_environment: false,
                        description: `PR #${pr.number} merged to main - marked as dev deployment`,
                      });

                      await github.rest.repos.createDeploymentStatus({
                        owner,
                        repo,
                        deployment_id: deployment.data.id,
                        state: 'success',
                        environment_url: '', // Optional: link to staging or preview site
                        description: 'Marked as deployed to dev',
                      });
