name: Create/Update Release Branch

on:
    push:
        branches:
            - main

jobs:
    create-release-branch:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Get version from versions.js
              id: get-version
              run: |
                  VERSION_MAJOR=$(node -p "require('./workspaces/react-native-apps/versions.js').APP_VERSION_MAJOR")
                  VERSION_MINOR=$(node -p "require('./workspaces/react-native-apps/versions.js').APP_VERSION_MINOR")
                  VERSION_PATCH=$(node -p "require('./workspaces/react-native-apps/versions.js').APP_VERSION_PATCH")

                  VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Version detected: $VERSION"

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Create or update release branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=${{ steps.get-version.outputs.version }}
                  RELEASE_BRANCH="release/$VERSION"

                  if git ls-remote --heads origin refs/heads/$RELEASE_BRANCH | grep -q refs/heads/$RELEASE_BRANCH; then
                    echo "Release branch $RELEASE_BRANCH exists. Updating..."
                    git checkout $RELEASE_BRANCH
                    git reset --hard origin/main
                    git push --force-with-lease origin $RELEASE_BRANCH
                  else
                    echo "Creating new release branch $RELEASE_BRANCH"
                    git checkout -b $RELEASE_BRANCH
                    git reset --hard origin/main
                    git push -u origin $RELEASE_BRANCH
                  fi
