name: Sync Branches

on:
    workflow_dispatch:
        inputs:
            source-branch:
                description: 'Source branch to sync from'
                required: true
                default: 'main'
            target-branch:
                description: 'Target branch to sync to'
                required: true
                default: 'dev'
            pr-title:
                description: 'Custom PR title'
                required: false
                default: 'Merge main into dev'
            pr-body:
                description: 'Custom PR description'
                required: false
                default: 'Automated PR to synchronize changes between branches'
            pr-reviewers:
                description: 'Comma-separated list of GitHub usernames of the reviewers (optional)'
                required: false

permissions:
    pull-requests: write
    contents: write

jobs:
    validate-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Validate Source Branch
              run: |
                  if [[ "${{ github.event.inputs.source-branch }}" != "main" ]]; then
                    echo "This workflow can only be triggered with 'main' as the source branch."
                    exit 1
                  fi
            - name: Validate Inputs
              run: |
                  if [[ -z "${{ github.event.inputs.pr-title }}" ]]; then
                      echo "Error: Pull request title is required." && exit 1
                  fi
                  if [[ -z "${{ github.event.inputs.target-branch }}" ]]; then
                      echo "Error: Target branch is required." && exit 1
                  fi
                  if [[ -z "${{ github.event.inputs.source-branch }}" ]]; then
                      echo "Error: Source branch is required." && exit 1
                  fi

    create-pr:
        needs: validate-trigger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Create Pull Request using GitHub CLI
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Create PR
                  pr_url=$(gh pr create \
                      --title "${{ github.event.inputs.pr-title }}" \
                      --body "${{ github.event.inputs.pr-body }}" \
                      --base "${{ github.event.inputs.target-branch }}" \
                      --head "${{ github.event.inputs.source-branch }}" \
                      --repo ${{ github.repository }} \
                      --label "automatic")

                  # Assign reviewers if any
                  if [[ -n "${{ github.event.inputs.pr-reviewers }}" ]]; then
                      IFS=',' read -ra REVIEWERS <<< "${{ github.event.inputs.pr-reviewers }}"
                      for reviewer in "${REVIEWERS[@]}"; do
                      gh pr review "$pr_url" --add-reviewer "$reviewer"
                      done
                  fi
