name: Sync Branches

on:
    workflow_dispatch:
        inputs:
            source-branch:
                description: 'Source branch to sync from'
                required: true
                default: 'main'
            target-branch:
                description: 'Target branch to sync to'
                required: true
                default: 'dev'
            pr-title:
                description: 'Custom PR title'
                required: false
                default: 'chore: sync branches'
            pr-body:
                description: 'Custom PR description'
                required: false
                default: 'Automated PR to synchronize changes between branches'

permissions:
    pull-requests: write
    contents: write

jobs:
    validate-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Validate Source Branch
              run: |
                  if [[ "${{ github.event.inputs.source-branch }}" != "main" ]]; then
                    echo "This workflow can only be triggered with 'main' as the source branch."
                    exit 1
                  fi

    create-pr:
        needs: validate-trigger
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ${{ inputs.target-branch }} # Set the base branch for the PR
                  branch: ${{ inputs.source-branch }} # Set the head branch for the PR
                  title: ${{ inputs.pr-title }}
                  body: ${{ inputs.pr-body }}
                  commit-message: 'Merge changes from ${{ inputs.source-branch }} to ${{ inputs.target-branch }}'
                  delete-branch: false
