name: Sync Branches

on:
    workflow_dispatch:
        inputs:
            source-branch:
                description: 'Source branch to sync from'
                required: true
                default: 'main'
            target-branch:
                description: 'Target branch to sync to'
                required: true
                default: 'dev'
            pr-title:
                description: 'Custom PR title'
                required: false
                default: 'chore: sync branches'
            pr-body:
                description: 'Custom PR description'
                required: false
                default: 'Automated PR to synchronize changes between branches'

permissions:
    pull-requests: write
    contents: write

jobs:
    validate-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Validate Source Branch
              run: |
                  if [[ "${{ github.event.inputs.source-branch }}" != "main" ]]; then
                    echo "This workflow can only be triggered with 'main' as the source branch."
                    exit 1
                  fi

    create-pr:
        needs: validate-trigger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Create Pull Request
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  API_URL="https://api.github.com/repos/${{ github.repository }}/pulls"
                  DATA=$(jq -n \
                      --arg title "${{ github.event.inputs.pr-title }}" \
                      --arg base "${{ github.event.inputs.target-branch }}" \
                      --arg head "${{ github.event.inputs.source-branch }}" \
                      --arg body "${{ github.event.inputs.pr-body }}" \
                      '{title: $title, head: $head, base: $base, body: $body}')
                  echo "Creating PR with data: $DATA"
                  curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      -d "$DATA" "$API_URL"
